language: node_js
node_js:
- node
env:
  global:
  - secure: tAH+xGz6NvZSet+THNUWaAOqyUy2WZlePrgIJn8FJLPd9p/pptL+B4/uvShSg4INz3/7hbizS9imJZzj+KZoQIyP5UHkoeq+e/EDbwoKeBPNVD4qx6L3SA6ccG7nGAAcRE+esgBpiHxm0Fcr9l7RtNkiLhA9lRAcOMHeJboj7rl8EvH5O3tz58B+Kl+m+6G6RS8FEGcJyCcbg25wQUcqXhHqxOMwBxuRz995G09M7hbyIfsFbJagkosfAFDNSA2yNxd8lTl6BRk4H7UtHi+GJs1Tffr8V5xABboVE0R69JB2K2l2fFbJEy1P12cBJltO0CKJ5GnriVSOF2K+lw1/T1fOiRB768Kbt/vnN7CabZGYZjSayfvdS7XvMHk8BFgC4K1e9UIJpFQyKUGpblk/4rVisSG+lZWfJkCjqv6HikgB9oE8X0vsxBeBxtdCwF+oyQx0Bjfcl5z5oplH48uxXukUSxrvvsdxDFpYnxLjyXbSXqXC3YeHutFCu2Hc/kg4hah0rCEMXfvhTSaBvH8WdT4xKvhHzeaWCdx1ftbxW3+eEmmQGk0UXMZgBdFCBOOU7N97kLI9VNqZldrKw97gs5t+rSIgqI1QsSYk878TnOYRtj9Xj60btc6TFZMpH0cleKooitYNZvvUD5gy6CrK7huXW91of30d/hIP3OT9xXc=
  - secure: BwF4Lgc0HWDQQBOoUvsrL9bhcp8Oh6qIDzXKa3F+Pi00wHE2PjmELhKFXgYY1ftKixDqUroXOFEAlldVVQ54bpmt2l/NQ3sssohEucTygt804y2mPIrNKAtIvUZ14Q+iGf7K0PmRsk9I0kL9GXKMs6VfAW6OBKsJPuhUm+6i13eFny15tpHNdAubhqA9pN+VR4dzEqQHmosuh8xytPFF39qN5+f1Gryd7q/RpqF404q7JSMQnCfxBKax6joMKisu0cRkhDpZZ90h+IQsZEh7/pFMqiXqX+yeTN1UVkIzSmzK4dAycT4WUay5Yp0Kx7mR5nhLO4L4KJUDBDRUozY0KlidIylpDRRy2LajYLQdWevAsIplv5pceCroWc/EVF+xFSoxw2QYVFkORfy+9MNu4CRu8m8RWMcEt06HLM1xGKOfdOZWaqu98ge4/Hf7SUsKGepMtk2QA+NqtN93aX0lfPUZX0U1VaMGiuXg/OnDh0CPI7jkw+hm8dj3t15/RjHyYpWzPpoTCqELt/4mYe85XprvxpWe0lqyskuWsek88PPmXHQWpaDgZmCtulWS2JVOkjFAFs06cxBurie8C2zBNRMzzCQVe4dr2j+AW5c2LnkKUVWGiHzmULcoUzFX5Zb5EMQ4dp/zpG1TLtONIETNF/UH3afvhh/Ad9PHWy4Ajrs=
script: npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
