language: node_js
node_js:
  - node
env:
  global:
  - secure: etbLgWFO09EUVuTZDCKGe3UG5zozPUT9EiUp5F1eMefdl8wqgpIhpHGrVlvImHwxmQEzetw9R7bzty4H3+4LygVf4f+p+8ghEV1h6AMPfk5FCYaPxf5/t34LHlFGy9sL89986Z+eEPubaLUf5ijhqGvm+DXH6Qk37saM1fGczNwrHsY/WTI3yizTgBppQUYtCLusu+tQrmuz+SW5TDLu1NRr3pXykbQlgIg/90/NtHwYXS+vpJ05OTzxPz2f49N9pE2xUmM6t6caX85KrMBB4MAxEO7P9MH7QENLa7T0O3y6z7aq+e8Jj/gx0stqv5WDQlRKK7vUZGsBekZzB5O9tuNceX7Gai19rRutQXlWL0kJVnOqpU/Y/63ddZ+ZyhCxLbrWbs29w7FN41gQxvriAlgx/ArGzohVLcFaMBL68s8yczsWL4g41hh3pviaPA3uPNqrWBYFXJRhxZKZx4UHiRtO0iRJftR/Vva/IqgCwr62POHKHe8ztWzzJ4WOPnuOMKCOerOIbqM2hYIVPkQ598Khs11jS+zRSmTzKiql0oAUZ2ZvPkYluYjeEYpvby0GMMzgETXUeWWIwe7dBI40KGauB+iX2FSkfexrH0cE/GNBlg0K/12IAZ4q57QR8Z7T4PMuor0c24gnp8BJhYu+ttvFdmNl/XTeTvdYwrQKB7c=
  - secure: EyPQiQ7Z5TX1FLvE5EgMFfcCPPQeD/mhkbud1hsxJwy5oZ9VvccPEnF4fPbUelOS9/OI0ccEXyHT4VRp4IIeIuXx3U0ZNrmXm4+uwHIXk1EdrnABCZmJyq/VeSPeWfGiyM5peAQU9+Da+agGYWympy8ELTyZzUmskSsf6RHq5dU+fu+1bztQ6Fcs+ab0S/09eoIBYF63bMu/8T80hjM8chXmrRKgYcmqQvf8TrC2GO9qk2sX3C9IWTZO6waN72Pwgi03ebH5h7VigdDCMNDgI9j80BuYZ5O3rOFAxbk4UW8zogY0NXhGaWAZlCwd+CA+rLXDjzt013yASSDE//+yTJFzk/DBSEa0Sf+rCuFNRsgLkL+KZXwKhP3yk6f/84Q24VfAwafM7B8TLbVxxnjq2Kse/2jhvz8IC6uX+PtvlNLFtp/e9qM4Jm/9hMPrmXBWnmgC0mT4LWRfdgvu01lXynIkGjaTvI1z/RwlDL8w6M4gbISthE+uTgCWwDHcbo2T3h4PPN/LLHYerPqss0WY3AtiDrPLBTx6CPjovdne6+XxLR+PRzwkei8k2HL7GsGWvWAMgDCom/JPiq5sIO1H876+r+5t6gA5LWsS9VONF6vCF0LIvUFXdB+a+YtNi4g7mqFNNJHLI1cfCPVr2g0BqvIUQS31g4JHwjtzEjAymVQ=
script: npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: continuous-deployment
